### ISSUE TITLE
Puzzles not detected finished (& 2 time trials)

### ISSUE THREAD

**Issue by SylverOmar** [Akebi-Private/Akebi-Issue-Tracker#75] opened 2023-01-19 13:15 UTC
many puzzles are not detected finished, like;
- primal sandglass
- torch puzzle
- cascade pools
- time trial
- ...

Btw there are 2 "time trial" elements to check in ESP

**Comment by ghost** [comment] 2023-01-20 15:23
Duplicate of #107

**Closed as completed by ghost** 2023-01-20 15:24 UTC
