### ISSUE TITLE
[BUG] Infinite stamina (move Sync Packet Replacment) not work for ayaka and Mona

### ISSUE THREAD

**Issue by WHOIAM121** [Akebi-Private/Akebi-Issue-Tracker#212] opened 2023-01-27 23:13 UTC
Stamina always runs out when Ayaka or Mona runs
please Fix this

**Comment by romanocry** [comment] 2023-01-30 23:12
hi, 
without changing anything in my config, Stamina is not working for all character... 
is anyone have same issue ?

**Comment by WHOIAM121** [comment] 2023-01-31 00:39
mine works fine for all characters except ayaka and mona, maybe i can help you if you show screenshots of what cheats you activated

**Comment by ghost** [comment] 2023-02-04 13:45
Duplicate of #207 #120

**Closed as completed by ghost** 2023-02-04 13:45 UTC
Labels: duplicate
